MusiciansApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusiciansApp.Model;
using MusiciansApp.Repository;

namespace MusiciansApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly MusicDbContext _context;

        public HomeController(MusicDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Search(string query)
        {
            query = query.ToLower();

            var artist = _context.Artists
                         .FirstOrDefault(a => a.Name.Contains(query));

            var song = _context.Songs
                        .FirstOrDefault(a => a.Title.Contains(query));

            var album = _context.Albums
                        .FirstOrDefault(a => a.Title.Contains(query));

            if (artist != null)
            {
                return RedirectToAction("ArtistDetails", new { artistId = artist.Id });
            }

            if (song != null)
            {
                return RedirectToAction("SongDetails", new { songId = song.Id });
            }

            if (album != null)
            {
                return RedirectToAction("AlbumDetails", new { albumId = album.Id });
            }

            ViewBag.Message = "Исполнитель, альбом или трек не найдены.";
            return View("Index");
        }

        [HttpGet]
        public IActionResult ArtistDetails(int artistId)
        {
            var artist = _context.Artists
                .Include(a => a.Albums)
                .ThenInclude(a => a.Songs)
                .Include(a => a.Singles)
                .FirstOrDefault(a => a.Id == artistId);

            if (artist == null)
            {
                return NotFound();
            }

            artist.Singles = _context.Songs
                .Where(s => s.ArtistId == artistId && (s.AlbumId == null || s.IsSingle))
                .ToList();

            return View(artist);
        }

        [HttpGet]
        public IActionResult SongDetails(int songId)
        {
            var song = _context.Songs
                        .Include(s => s.Artist)
                        .ThenInclude(s => s.Albums)
                        .FirstOrDefault(s => s.Id == songId);

            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        [HttpGet]
        public IActionResult AlbumDetails(int albumId)
        {
            var album = _context.Albums
                        .Include(s => s.Artist)
                        .Include(s => s.Songs)
                        .FirstOrDefault(s => s.Id == albumId);

            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }
    }
}

MusiciansApp/Controllers/TracksController.cs
using Microsoft.AspNetCore.Mvc;
using MusiciansApp.Model;
using MusiciansApp.Repository;

namespace MusiciansApp.Controllers
{
    public class TracksController : Controller
    {
        private readonly MusicDbContext _context;

        public TracksController(MusicDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult AddTrack()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddTrack(string title, string musician, IFormFile trackFile)
        {
            if (musician != null && trackFile != null && trackFile.ContentType == "audio/mpeg")
            {
                var fileName = $"{Guid.NewGuid()}_{trackFile.FileName}";
                var filePath = Path.Combine("wwwroot/Uploads", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    trackFile.CopyTo(stream);
                }

                var track = new Track
                {
                    Title = title,
                    Musician = musician,
                    FilePath = $"/Uploads/{fileName}"
                };

                _context.Tracks.Add(track);
                _context.SaveChanges();

                TempData["SuccessMessageTrack"] = "Трек успешно добавлен!";
                return RedirectToAction("Index", "Artists");
            }

            TempData["ErrorMessageTrack"] = "Загрузите MP3 файл.";
            return View();
        }

        [HttpGet]
        public IActionResult SearchTrack(string name)
        {
            var tracks = _context.Tracks
                         .Where(a => a.Musician.Contains(name))
                         .ToList();

            if (tracks.Any())
            {
                return View("Discography", tracks);
            }
            else
            {
                ViewBag.Message = "Исполнитель не найден.";
                return View();
            }
        }
    }
}

MusiciansApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusiciansApp.Model;
using MusiciansApp.Repository;
using SQLitePCL;

namespace MusiciansApp.Controllers
{
    public class UsersController : Controller
    {

        private readonly MusicDbContext _context;

        public UsersController(MusicDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }

            if (_context.Users.Any(a => a.UserName == user.UserName || a.Email == user.Email))
            {
                ModelState.AddModelError("", " Пользователь с таким именем или email уже существует.");
                return View(user);
            }

            _context.Users.Add(user);
            _context.SaveChanges();
            _context.Database.ExecuteSqlRaw("UPDATE sqlite_sequence SET seq = 1 WHERE name = 'users'");


            TempData["SuccessMessageRegister"] = "Регистрация прошла успешно!";

            return RedirectToAction("Login", "Users");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string name, string password)
        {
            var user = _context.Users.FirstOrDefault(a => a.UserName == name && a.Password == password);

            if (user == null)
            {
                TempData["ErrorMessage"] = "Неверное имя пользователя или пароль.";
                return View();
            }

            TempData["UserName"] = user.UserName;
            TempData["SuccessMessageLogin"] = "Вы успешно вошли в систему!";

            return RedirectToAction("SongDetails", "Songs");
        }
    }
}

MusiciansApp/Views/Home/AlbumDetails.cshtml
@model MusiciansApp.Model.Album

<link href="~/Styles/AlbumDetails.css" rel="stylesheet" />

<div class="album-details-container">
    <h2 class="album-title">@Model.Title</h2>

    @if (Model.Artist != null)
    {
        <p><strong>Исполнитель:</strong> <a href="@Url.Action("ArtistDetails", "Home", new { artistId = Model.Artist.Id })">@Model.Artist.Name</a></p>
    }
    else
    {
        <p><strong>Исполнитель:</strong> Не указан</p>
    }

    <div class="album-info">
        @if (!string.IsNullOrEmpty(Model.ImagePath))
        {
            <img src="@Model.ImagePath" alt="@Model.Title" class="album-cover" />
        }
    </div>

    <h3 class="track-list-title">Список треков</h3>
    @if (Model.Songs != null && Model.Songs.Any())
    {
        <ul class="track-list">
            @foreach (var track in Model.Songs)
            {
                <li>
                    @track.Title
                    @if (!string.IsNullOrEmpty(track.FilePath))
                    {
                        <div>
                            <audio controls>
                                <source src="@track.FilePath" type="audio/mpeg">
                                Ваш браузер не поддерживает воспроизведение аудио.
                            </audio>
                        </div>
                    }
                </li>
            }
        </ul>
    }
    else
    {
        <p>Треки для этого альбома не найдены.</p>
    }

    <div class="back-link">
        <a href="@Url.Action("Index", "Home")">На главную</a>
    </div>
</div>

MusiciansApp/Views/Home/ArtistDetails.cshtml
@model MusiciansApp.Model.Artist

<link href="~/Styles/ArtistsDetails.css" rel="stylesheet" />

<div class="artist-container">
    <h2>@Model.Name</h2>
    <img src="@Model.ImagePath" alt="@Model.Name" class="artist-image" />

    <div class="content-container">
        <div class="albums-container">
            <h3>Альбомы</h3>
            @if (Model.Albums != null && Model.Albums.Any())
            {
                <ul class="album-list">
                    @foreach (var album in Model.Albums)
                    {
                        <li class="album-item">
                            <h4>@album.Title (@album.ReleaseDate.ToString("yyyy"))</h4>
                            <img src="@album.ImagePath" alt="@album.Title" class="album-cover" />

                            @if (album.Songs != null && album.Songs.Any())
                            {
                                <ul class="song-list">
                                    @foreach (var song in album.Songs)
                                    {
                                        <li>
                                            @song.Title
                                            @if (!string.IsNullOrEmpty(song.FilePath))
                                            {
                                                <div>
                                                    <audio controls>
                                                        <source src="@song.FilePath" type="audio/mpeg">
                                                    </audio>
                                                </div>
                                            }
                                        </li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <p>Песни в этом альбоме не найдены.</p>
                            }
                        </li>
                    }
                </ul>
            }
            else
            {
                <p>Альбомы для этого исполнителя не найдены.</p>
            }
        </div>

        <div class="singles-container">
            <h3>Синглы и отдельные треки</h3>
            @if (Model.Singles != null && Model.Singles.Any())
            {
                <ul class="single-list">
                    @foreach (var song in Model.Singles)
                    {
                        <li>
                            <img src="@song.ImagePath" alt="@song.Title" class="single-image" />
                            @song.Title

                            @if (!string.IsNullOrEmpty(song.FilePath))
                            {
                                <div>
                                    <audio controls>
                                        <source src="@song.FilePath" type="audio/mpeg">
                                    </audio>
                                </div>
                            }
                        </li>
                    }
                </ul>
            }
            else
            {
                <p>У этого исполнителя нет отдельных треков.</p>
            }
        </div>
    </div>
</div>

MusiciansApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Поиск исполнителя";
}
<link href="~/Styles/Index.css" rel="stylesheet"/>

<div class="reg-auth-buttons">
    <div>
        <form action="/Users/Register" method="get">
            <button type="submit">Регистрация</button>
        </form>
    </div>

    <div>
        <form action="/Users/Login" method="get">
            <button type="submit">Войти</button>
        </form>
    </div>
</div>

<div class="container">
    <form action="/Home/Search" method="get">
        <input type="text" name="query">
        <button type="submit">Найти</button>
    </form>
</div>

<div>
    <form action="/Tracks/SearchTrack" method="get">
        <input type="text" placeholder="Введите имя музыканта" name="name">
        <button type="submit">Найти</button>
    </form>
</div>

<br/>


@if (TempData["SuccessMessageLogin"] != null)
{
    <p>@TempData["SuccessMessageLogin"]</p>
}

@if (TempData["SuccessMessageTrack"] != null)
{
    <p>@TempData["SuccessMessageTrack"]</p>
}

MusiciansApp/Views/Home/SongDetails.cshtml
@model MusiciansApp.Model.Song

<link href="~/Styles/SongDetails.css" rel="stylesheet" />

<div class="track-details-container">

    <div class="track-info">
        <h3>@Model.Title</h3>

        @if (Model.Artist != null)
        {
            <p><strong>Исполнитель:</strong> <a href="@Url.Action("ArtistDetails", "Home", new { artistId = Model.Artist.Id })">@Model.Artist.Name</a></p>
        }
        else
        {
            <p><strong>Исполнитель:</strong> Не указан</p>
        }

        @if (Model.Album != null)
        {
            <p><strong>Альбом:</strong> <a href="@Url.Action("AlbumDetails", "Home", new { albumId = Model.Album.Id })">@Model.Album.Title</a></p>
        }
        else
        {
            <p><strong>Альбом:</strong> Не указан</p>
        }

        @if (!string.IsNullOrEmpty(Model.FilePath))
        {
            <div>
                <audio controls>
                    <source src="@Model.FilePath" type="audio/mpeg">
                    Ваш браузер не поддерживает воспроизведение аудио.
                </audio>
            </div>
        }
        else
        {
            <p>Аудиофайл недоступен.</p>
        }

        @if (!string.IsNullOrEmpty(Model.ImagePath))
        {
            <img src="@Model.ImagePath" alt="@Model.Title" class="track-cover" />
        }
    </div>

    <div class="back-link">
        <a href="@Url.Action("Index", "Home")">Назад на главную</a>
    </div>
</div>

MusiciansApp/Views/Tracks/AddTrack.cshtml
@model MusiciansApp.Model.Track
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Добавить трек";
}

<h2>Добавить трек</h2>

<form asp-action="AddTrack" asp-controller="Tracks" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Musician">Исполнитель</label>
        <input asp-for="Musician" name="musician" type="text" class="form-control" placeholder="Введите название трека" required />
    </div>

    <div class="form-group">
        <label asp-for="Title">Название трека</label>
        <input asp-for="Title" name="title" type="text" class="form-control" placeholder="Введите название трека" required />
    </div>

    <div class="form-group">
        <label asp-for="FilePath">Выберите MP3 файл</label>
        <input asp-for="FilePath" name="trackFile" type="file" accept=".mp3" class="form-control" required />
    </div>

    <button type="submit" class="btn btn-primary">Загрузить</button>
</form>

MusiciansApp/Views/Tracks/Discography.cshtml
@model List<MusiciansApp.Model.Track>

<h2>Дискография исполнителя</h2>

@if (Model.Count > 0)
{
    <ul>
        @foreach (var track in Model)
        {
            <li>
                <strong>@track.Title</strong> - @track.Musician
                <br />
                <audio controls>
                    <source src="@track.FilePath" type="audio/mpeg">
                    Ваш браузер не поддерживает воспроизведение аудиофайлов.
                </audio>
            </li>
        }
    </ul>
}
else
{
    <p>Треки не найдены.</p>
}

MusiciansApp/Views/Users/Login.cshtml
@model MusiciansApp.Model.User
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="stylesheet" href="~/Styles/Login.css">
</head>
<body>
    <div class="auth-container">
        <div class="auth-box">
            <h2>Войти в аккаунт</h2>
            <form asp-action="Login" asp-controller="Users">
                <div class="form-group">
                    <label asp-for="UserName">Имя пользователя</label>
                    <input asp-for="UserName" name="name" type="text" placeholder="Введите имя пользователя" />
                </div>
                <div class="form-group">
                    <label asp-for="Password">Пароль</label>
                    <input asp-for="Password" name="password" type="password" placeholder="Введите пароль">
                </div>
                <div class="form-group">
                    <button type="submit" class="auth-button">Войти</button>
                </div>
                <p class="register-link">Нет аккаунта? <a asp-action="Register" asp-controller="Users">Зарегистрироваться</a></p>
            </form>
        </div>
    </div>

    @if (TempData["ErrorMessage"] != null)
    {
        <p>@TempData["ErrorMessage"]</p>
    }
</body>
</html>

MusiciansApp/Views/Users/Register.cshtml
@model MusiciansApp.Model.User
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="stylesheet" href="~/Styles/Register.css">

</head>
<body>
    <div class="auth-container">
        <div class="auth-box">
            <h2>Регистрация</h2>

            <form asp-controller="Users" asp-action="Register" method="post">

                <div class="form-group">
                    <label asp-for="UserName">Имя пользователя</label>
                    <input asp-for="UserName" placeholder="Введите имя пользователя" />
                    <span asp-validation-for="UserName" class="text-danger" ></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email">Email</label>
                    <input asp-for="Email"  placeholder="Введите email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password">Пароль</label>
                    <input asp-for="Password" type="password" placeholder="Введите пароль" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
             
                <div class="form-group">
                    <button type="submit" class="auth-button">Зарегистрироваться</button>
                </div>
                <p class="login-link">Уже есть аккаунт? <a asp-action="Login" asp-controller="Users">Войти</a></p>
            </form>

        </div>
    </div>
</body>
</html>